### ISSUE TITLE
Panic not managed if pcvalidate runs in a different path from the file publiccode.yml

### ISSUE THREAD

**Issue by lorello** [italia/publiccode-parser-go#12]
The pcvalidate utility exits with a panic error if I try to validate a file from a distinct directory where the file to be validated resides. 

Example:
```
lorello@calcifer:~/src/opencontent/openagenda$ docker run -v $(pwd):/var/tmp:ro -it --rm golang sh -c "go get github.com/italia/publiccode-parser-go/pcvalidate; bin/pcvalidate /var/tmp/publiccode.yml"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x4ee7c6]

goroutine 1 [running]:
github.com/alranel/go-vcsurl.IsRawFile(0x0, 0x17)
    /go/src/github.com/alranel/go-vcsurl/vcsurl.go:95 +0x26
github.com/alranel/go-vcsurl.IsFile(0x0, 0x4cbbee)
    /go/src/github.com/alranel/go-vcsurl/vcsurl.go:72 +0x2f
github.com/alranel/go-vcsurl.GetRawRoot(0x0, 0x0)
    /go/src/github.com/alranel/go-vcsurl/vcsurl.go:139 +0x2f
main.main()
    /go/src/github.com/italia/publiccode-parser-go/pcvalidate/pcvalidate.go:43 +0x70d
```

The problem does not occur if I run the command from the same path where the `publiccode.yml` resides:
```
lorello@calcifer:~/src/opencontent/openagenda$ docker run -v $(pwd):/var/tmp:ro -it --rm golang sh -c "go get github.com/italia/publiccode-parser-go/pcvalidate; cd /var/tmp; /go/bin/pcvalidate publiccode.yml"
validation ko:
description/it/features: too long, max 100 chars
```

**Comment by libremente** [comment]
Thanks @lorello, this issue has been open for quite a while unfortunately, we will try to tackle it ASAP, thanks for your patience!
